"""
Notification Engine
Creates a GitHub issue with new worthy mentions.
Uses GitHub repository notifications for the owner/watchers.

Requires GitHub Actions variables:
  - GITHUB_TOKEN: set automatically by GitHub Actions
  - GITHUB_REPOSITORY: set automatically as owner/repo
"""

import csv
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
CONFIG_DIR = ROOT / "config"

with open(CONFIG_DIR / "scoring.json") as f:
    SCORING = json.load(f)

THRESHOLDS = SCORING["thresholds"]

GITHUB_API_URL = os.environ.get("GITHUB_API_URL", "https://api.github.com")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPOSITORY = os.environ.get("GITHUB_REPOSITORY", "sbc1-code/brand-monitor")
PAGES_URL = os.environ.get("PAGES_URL", "https://sbc1-code.github.io/brand-monitor/")


def load_csv(filepath):
    if not filepath.exists():
        return []
    with open(filepath, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def format_mention_markdown(mention):
    """Format a single mention as GitHub-flavored markdown."""
    score = mention.get("signal_score", "?")
    title = mention.get("title", "Untitled")
    url = mention.get("url", "")
    brand = mention.get("brand_name", "")
    product = mention.get("product", "")
    source = mention.get("source_name", "")
    source_type = mention.get("source_type", "").replace("_", " ").title()
    pub_date = mention.get("published_date", "unknown")
    snippet = mention.get("snippet", "")[:300]
    sentiment = mention.get("sentiment", "neutral")

    sent_icon = {"positive": "+", "negative": "!", "neutral": "~"}.get(sentiment, "~")

    lines = [
        f"### [{title}]({url})",
        f"**Brand:** {brand} | **Product:** {product}",
        f"**Source:** {source} ({source_type}) | **Published:** {pub_date}",
        f"**Signal Score:** {score} | **Sentiment:** {sentiment} ({sent_icon})",
        "",
    ]
    if snippet:
        lines.append(f"> {snippet}")
        lines.append("")

    return "\n".join(lines)


def create_github_issue(scored_mentions):
    """Create a GitHub issue with the daily scan results."""
    if not GITHUB_TOKEN:
        print("[WARN] No GITHUB_TOKEN set. Skipping issue creation.")
        print("GitHub Actions sets GITHUB_TOKEN automatically.")
        return None

    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    date_display = now.strftime("%B %d, %Y")

    highlights = [
        m for m in scored_mentions
        if int(m.get("signal_score", 0)) >= THRESHOLDS["highlight"]
    ]
    worthy = [
        m for m in scored_mentions
        if int(m.get("signal_score", 0)) >= THRESHOLDS["notify"]
    ]
    other = [
        m for m in scored_mentions
        if int(m.get("signal_score", 0)) < THRESHOLDS["notify"]
    ]

    body_parts = [
        f"## Brand Mentions Scan - {date_display}",
        "",
        f"**New mentions found:** {len(scored_mentions)}",
        f"**Above notify threshold ({THRESHOLDS['notify']}):** {len(worthy)}",
        f"**Highlights ({THRESHOLDS['highlight']}+):** {len(highlights)}",
        "",
        f"[View full report]({PAGES_URL})",
        "",
    ]

    if highlights:
        body_parts.append("---")
        body_parts.append("## Highlights")
        body_parts.append("")
        for mention in highlights:
            body_parts.append(format_mention_markdown(mention))

    if worthy:
        non_highlight_worthy = [
            m for m in worthy
            if int(m.get("signal_score", 0)) < THRESHOLDS["highlight"]
        ]
        if non_highlight_worthy:
            body_parts.append("---")
            body_parts.append("## Notable Mentions")
            body_parts.append("")
            for mention in non_highlight_worthy:
                body_parts.append(format_mention_markdown(mention))

    if other:
        body_parts.append("---")
        body_parts.append("<details>")
        body_parts.append(f"<summary>Other mentions ({len(other)})</summary>")
        body_parts.append("")
        for mention in other:
            body_parts.append(format_mention_markdown(mention))
        body_parts.append("</details>")

    body_parts.append("")
    body_parts.append("---")
    body_parts.append(f"*Generated by Brand Monitor pipeline on {date_display}*")

    payload = {
        "title": f"Brand Mentions: {date_str} ({len(worthy)} worthy, {len(highlights)} highlights)",
        "body": "\n".join(body_parts),
        "labels": ["brand-monitor", "automated"],
    }
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    try:
        resp = requests.post(
            f"{GITHUB_API_URL}/repos/{GITHUB_REPOSITORY}/issues",
            headers=headers,
            json=payload,
            timeout=30,
        )
        resp.raise_for_status()
        issue = resp.json()
        print(f"GitHub issue created: {issue.get('html_url')}")
        return issue
    except Exception as e:
        print(f"[ERROR] Failed to create GitHub issue: {e}", file=sys.stderr)
        return None


def main():
    scored_file = DATA_DIR / "scored_mentions.csv"

    print("=== Notification ===")

    flag = DATA_DIR / "scan_result.txt"
    if flag.exists():
        status = flag.read_text().strip()
        if status == "NO_NEW_MENTIONS":
            print("No new mentions. No notification needed.")
            return 0
        if status == "NO_WORTHY_MENTIONS":
            print("No worthy mentions. Skipping notification.")
            return 0

    scored = load_csv(scored_file)
    if not scored:
        print("No scored mentions to notify about.")
        return 0

    worthy = [
        m for m in scored
        if int(m.get("signal_score", 0)) >= THRESHOLDS["notify"]
    ]
    if not worthy:
        print("No mentions above notify threshold. Skipping.")
        return 0

    print(f"Worthy mentions to notify: {len(worthy)}")

    issue = create_github_issue(scored)
    if issue:
        print(f"Notification sent via GitHub issue #{issue.get('number')}")
    else:
        print("Issue creation skipped or failed.")

    return len(worthy)


if __name__ == "__main__":
    count = main()
    sys.exit(0)
