"""
Notification Engine
Creates a GitLab issue with new worthy mentions.
Uses GitLab's built-in notifications to email the configured project assignee.

Requires CI/CD variables:
  - GITLAB_TOKEN: Project access token or personal access token
  - CI_PROJECT_ID: Set automatically by GitLab CI
  - GITLAB_API_URL: Your GitLab instance API URL (e.g. https://gitlab.example.com/api/v4)
"""

import csv
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
CONFIG_DIR = ROOT / "config"

with open(CONFIG_DIR / "scoring.json") as f:
    SCORING = json.load(f)

THRESHOLDS = SCORING["thresholds"]

# GitLab API config — set these as CI/CD variables in your GitLab project
GITLAB_URL = os.environ.get("CI_API_V4_URL", "https://gitlab.example.com/api/v4")
GITLAB_TOKEN = os.environ.get("GITLAB_TOKEN", "")
PROJECT_ID = os.environ.get("CI_PROJECT_ID", "YOUR_PROJECT_ID")
ASSIGNEE_ID = os.environ.get("NOTIFY_ASSIGNEE_ID", "1")  # Set to your GitLab user ID
PAGES_URL = os.environ.get("CI_PAGES_URL", "https://pages.example.com/brand-monitor")


def load_csv(filepath):
    if not filepath.exists():
        return []
    with open(filepath, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def format_mention_markdown(mention):
    """Format a single mention as GitLab-flavored markdown."""
    score = mention.get("signal_score", "?")
    title = mention.get("title", "Untitled")
    url = mention.get("url", "")
    brand = mention.get("brand_name", "")
    product = mention.get("product", "")
    source = mention.get("source_name", "")
    source_type = mention.get("source_type", "").replace("_", " ").title()
    pub_date = mention.get("published_date", "unknown")
    snippet = mention.get("snippet", "")[:300]
    sentiment = mention.get("sentiment", "neutral")

    # Sentiment indicator
    sent_icon = {"positive": "+", "negative": "!", "neutral": "~"}.get(sentiment, "~")

    lines = [
        f"### [{title}]({url})",
        f"**Brand:** {brand} | **Product:** {product}",
        f"**Source:** {source} ({source_type}) | **Published:** {pub_date}",
        f"**Signal Score:** {score} | **Sentiment:** {sentiment} ({sent_icon})",
        "",
    ]
    if snippet:
        lines.append(f"> {snippet}")
        lines.append("")

    return "\n".join(lines)


def create_gitlab_issue(scored_mentions):
    """Create a GitLab issue with the daily scan results."""
    if not GITLAB_TOKEN:
        print("[WARN] No GITLAB_TOKEN set. Skipping issue creation.")
        print("Set GITLAB_TOKEN in CI/CD variables to enable notifications.")
        return None

    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    date_display = now.strftime("%B %d, %Y")

    # Separate by threshold
    highlights = [m for m in scored_mentions if int(m.get("signal_score", 0)) >= THRESHOLDS["highlight"]]
    worthy = [m for m in scored_mentions if int(m.get("signal_score", 0)) >= THRESHOLDS["notify"]]
    other = [m for m in scored_mentions if int(m.get("signal_score", 0)) < THRESHOLDS["notify"]]

    # Build issue body
    body_parts = [
        f"## Brand Mentions Scan - {date_display}",
        "",
        f"**New mentions found:** {len(scored_mentions)}",
        f"**Above notify threshold ({THRESHOLDS['notify']}):** {len(worthy)}",
        f"**Highlights ({THRESHOLDS['highlight']}+):** {len(highlights)}",
        "",
        f"[View full report]({PAGES_URL})",
        "",
    ]

    if highlights:
        body_parts.append("---")
        body_parts.append("## Highlights")
        body_parts.append("")
        for m in highlights:
            body_parts.append(format_mention_markdown(m))

    if worthy:
        non_highlight_worthy = [m for m in worthy if int(m.get("signal_score", 0)) < THRESHOLDS["highlight"]]
        if non_highlight_worthy:
            body_parts.append("---")
            body_parts.append("## Notable Mentions")
            body_parts.append("")
            for m in non_highlight_worthy:
                body_parts.append(format_mention_markdown(m))

    if other:
        body_parts.append("---")
        body_parts.append("<details>")
        body_parts.append(f"<summary>Other mentions ({len(other)})</summary>")
        body_parts.append("")
        for m in other:
            body_parts.append(format_mention_markdown(m))
        body_parts.append("</details>")

    body_parts.append("")
    body_parts.append("---")
    body_parts.append(f"*Generated by Brand Monitor pipeline on {date_display}*")

    description = "\n".join(body_parts)
    title = f"Brand Mentions: {date_str} ({len(worthy)} worthy, {len(highlights)} highlights)"

    # Create the issue
    headers = {"PRIVATE-TOKEN": GITLAB_TOKEN}
    payload = {
        "title": title,
        "description": description,
        "assignee_ids": [int(ASSIGNEE_ID)],
        "labels": "brand-monitor,automated",
    }

    try:
        resp = requests.post(
            f"{GITLAB_URL}/projects/{PROJECT_ID}/issues",
            headers=headers,
            json=payload,
            timeout=30
        )
        resp.raise_for_status()
        issue = resp.json()
        print(f"GitLab issue created: {issue.get('web_url')}")
        return issue
    except Exception as e:
        print(f"[ERROR] Failed to create GitLab issue: {e}", file=sys.stderr)
        return None


def main():
    scored_file = DATA_DIR / "scored_mentions.csv"

    print("=== Notification ===")

    # Check flag
    flag = DATA_DIR / "scan_result.txt"
    if flag.exists():
        status = flag.read_text().strip()
        if status == "NO_NEW_MENTIONS":
            print("No new mentions. No notification needed.")
            return 0
        if status == "NO_WORTHY_MENTIONS":
            print("No worthy mentions. Skipping notification.")
            return 0

    # Load scored mentions
    scored = load_csv(scored_file)
    if not scored:
        print("No scored mentions to notify about.")
        return 0

    # Filter to worthy
    worthy = [m for m in scored if int(m.get("signal_score", 0)) >= THRESHOLDS["notify"]]
    if not worthy:
        print("No mentions above notify threshold. Skipping.")
        return 0

    print(f"Worthy mentions to notify: {len(worthy)}")

    # Create GitLab issue
    issue = create_gitlab_issue(scored)
    if issue:
        print(f"Notification sent via GitLab issue #{issue.get('iid')}")
    else:
        print("Issue creation skipped or failed.")

    return len(worthy)


if __name__ == "__main__":
    count = main()
    sys.exit(0)
